services:
  - type: web
    name: notes-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
        